ssl_certificate         /etc/letsencrypt/manage.pp.ua/fullchain1.pem;
ssl_certificate_key     /etc/letsencrypt/manage.pp.ua/privkey1.pem;
ssl_trusted_certificate /etc/letsencrypt/manage.pp.ua/chain1.pem;
