ARG PHP_VER

FROM php:$PHP_VER

# Arguments defined in docker-compose.yml
	ARG APP_USER
	ARG APP_UID	
# Install system dependencies
	RUN apt-get update \
	  && apt-get install -y \
		 apt-utils \
		 git \
		 vim \
		 man \
		 curl \
		 pkg-config \
		 icu-devtools \
		 libicu-dev \
		 libcurl4 \
		 libfreetype6-dev \
		 libjpeg62-turbo-dev \
		 libpng-dev \
		 libjpeg-dev \
		 libbz2-dev \
		 libssl-dev \
		 libgmp-dev \
		 libtidy-dev \
		 libxml2-dev \
		 libxslt1-dev \
		 libzip-dev \
		 libonig-dev \
		 libcurl4-openssl-dev \
		 autoconf \
	  &&  ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h

	RUN docker-php-ext-install mysqli \
		&& docker-php-ext-install pdo_mysql \
		&& docker-php-ext-install intl \
		&& docker-php-ext-install zip \
		&& docker-php-ext-install bz2 \
		&& docker-php-ext-install calendar \
		&& docker-php-ext-install bcmath \
		&& docker-php-ext-install exif \
		&& docker-php-ext-install gettext \
		&& docker-php-ext-install gmp \
		&& docker-php-ext-install mbstring \
		&& docker-php-ext-install pcntl \
		&& docker-php-ext-install shmop \
		&& docker-php-ext-install sockets \
		&& docker-php-ext-install sysvmsg \
		&& docker-php-ext-install sysvsem \
		&& docker-php-ext-install sysvshm \
		&& docker-php-ext-install tidy \
		&& docker-php-ext-install xsl \
		&& docker-php-ext-install gd \
		&& docker-php-ext-install curl \
		&& docker-php-source delete
		
	RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
	  && docker-php-ext-install -j$(nproc) gd \
	  && docker-php-source delete
	
	RUN apt update && apt install -y git

# Install node and npm in container
	RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
	apt-get install -y nodejs
	
# Install vue/cli in container
	RUN npm install -g @vue/cli

# php.ini
    ADD ./php-fpm/php.ini /usr/local/etc/php/conf.d/

# Get latest Composer
	COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
	RUN useradd -G www-data,root -u $APP_UID -d /home/$APP_USER $APP_USER
	RUN mkdir -p /home/$APP_USER/.composer && chown -R $APP_USER:$APP_USER /home/$APP_USER

# Clear cache
	RUN apt-get clean && rm -rf /var/lib/apt/lists/*
	
USER $APP_USER