server {
        index index.php index.html;
        server_name heater-new.home-kl.pp.ua heater.loc;
        error_log /var/log/nginx/heater.error.log;
        access_log /var/log/nginx/heater.access.log;
        root /var/www/heater/public;
		
	location / {
		try_files $uri $uri/ $uri.html /index.php?$args;
		gzip_static on;
	}
        location ~ \.php$ {
            include /etc/nginx/php_fastcgi.conf;
        }
    }
