server {
		listen 					80;
		listen                  443 ssl;
		listen                  [::]:443 ssl;
		server_name             manage.pp.ua manage.loc;
		set                     $base /var/www/heater;
		root                    $base/public;

		# SSL
		include 				/etc/nginx/user.d/ssl_cert.conf;

		# security
		include                 /etc/nginx/user.d/security.conf;

        index index.php index.html;
        error_log /var/log/nginx/manage.error.log;
        access_log /var/log/nginx/manage.access.log;
		
	location / {
		try_files $uri $uri/ $uri.html /index.php?$args;
		gzip_static on;
	}
        location ~ \.php$ {
			try_files $uri =404;
            include /etc/nginx/user.d/php_fastcgi.conf;
        }
    }
# subdomains redirect
server {
    listen                  443 ssl;
    listen                  [::]:443 ssl;
    server_name             *.manage.pp.ua;

    # SSL
	include 				/etc/nginx/user.d/ssl_cert.conf;
    return                  301 https://manage.pp.ua$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .manage.pp.ua;
    include     /etc/nginx/user.d/letsencrypt.conf;

    location / {
        return 301 https://manage.pp.ua$request_uri;
    }
}