server {
		listen                  443 ssl;
		listen                  [::]:443 ssl;
		server_name             manage.pp.ua;
		set                     $base /var/www/heater;
		root                    $base/public;

		# SSL
		ssl_certificate         /etc/letsencrypt/manage.pp.ua/fullchain1.pem;
		ssl_certificate_key     /etc/letsencrypt/manage.pp.ua/privkey1.pem;
		ssl_trusted_certificate /etc/letsencrypt/manage.pp.ua/chain1.pem;

		# security
		include                 /etc/nginx/security.conf;

        index index.php index.html;
        error_log /var/log/nginx/manage.error.log;
        access_log /var/log/nginx/manage.access.log;
		
	location / {
		try_files $uri $uri/ $uri.html /index.php?$args;
		gzip_static on;
	}
        location ~ \.php$ {
            include /etc/nginx/php_fastcgi.conf;
        }
    }
# subdomains redirect
server {
    listen                  443 ssl;
    listen                  [::]:443 ssl;
    server_name             *.manage.pp.ua;

    # SSL
    ssl_certificate         /etc/letsencrypt/manage.pp.ua/fullchain1.pem;
    ssl_certificate_key     /etc/letsencrypt/manage.pp.ua/privkey1.pem;
    ssl_trusted_certificate /etc/letsencrypt/manage.pp.ua/chain1.pem;
    return                  301 https://manage.pp.ua$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .manage.pp.ua;
    include     letsencrypt.conf;

    location / {
        return 301 https://manage.pp.ua$request_uri;
    }
}